### ISSUE TITLE
OCSP Must Staple extension is reported as Error by certlint

### ISSUE THREAD

**Issue by martinsuchan** [awslabs/certlint#33] opened 2016-05-27 18:01 UTC
See this log:
https://crt.sh/?cablint=72&iCAID=16418
Or this certificate:
https://crt.sh/?id=20290798&opt=cablint

CA/B Forum lint reports error:

> ERROR: Unknown Extension: 1.3.6.1.5.5.7.1.24

This Id represents the [OCSP Must Staple extension](https://security.stackexchange.com/questions/119316/how-to-simply-check-if-a-certificate-has-the-ocsp-must-staple-attribute) as [described in this RFC](https://tools.ietf.org/html/rfc7633#section-6)

**Comment by robstradling** [comment] 2016-06-09 10:38
Duplicate of ticket #25.

**Closed as completed** 2016-08-16 20:48 UTC
