### ISSUE TITLE
Show error when keyAgreement is set for ECDSA certs

### ISSUE THREAD

**Issue by WilsonKathleen** [awslabs/certlint#17] opened 2016-02-09 00:48 UTC
https://bugzilla.mozilla.org/show_bug.cgi?id=1201423#c20
"Additionally I agree with Fotis Loukos that keyAgreement is not correct when the key is expected to be used with ECDSA."

**Comment by selecadm** [comment] 2016-02-12 10:22
https://crt.sh/?id=4466285&opt=cablint
ERROR: Unallowed key usage for EC public key
X509v3 Key Usage: critical
Digital Signature, Key Encipherment

https://crt.sh/?id=4964923&opt=cablint
X509v3 Key Usage: critical
Digital Signature, Key Agreement

While Key Encipherment is useless, Key Agreement is dangerous, so there should be even a bigger warning for the latter. DigiCert, oh you…

**Comment by pzb** [comment] 2016-02-12 17:35
Can you find a RFC or other applicable standard that updates https://tools.ietf.org/html/rfc5480?  

5480 says:

```
   If the keyUsage extension is present in an End Entity (EE)
   certificate that indicates id-ecPublicKey in SubjectPublicKeyInfo,
   then any combination of the following values MAY be present:

     digitalSignature;
     nonRepudiation; and
     keyAgreement.

   If the EE certificate keyUsage extension asserts keyAgreement, then
   it MAY assert either encipherOnly or decipherOnly.
```

**Comment by pzb** [comment] 2017-06-19 00:09
It seems my comment in bugzilla was unjustified.  I'm closing this as working as intended.

**Closed as completed by pzb** 2017-06-19 00:09 UTC
